
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NUM VAR\n    Calculadora : ATRIB  \n                | VALVAR\n                | VALEXP\n                | DUMP\n    \n    ATRIB : VAR "=" EXP\n    \n    VALVAR : "?" VAR\n    \n    VALEXP : "!" EXP\n    \n    DUMP : "*"\n    \n    EXP : MENOS\n        | MAIS\n        | TERM    \n    \n    MAIS : EXP "+" TERM\n    \n    MENOS : EXP "-" TERM\n    \n    \n    TERM : MULT\n         | DIV\n         | FACTOR\n    \n    MULT : TERM "*" FACTOR \n    \n    DIV : TERM "/" FACTOR\n    \n    FACTOR : NUM\n           | PA\n           | VAR\n    \n    PA : "(" EXP ")"\n    '
    
_lr_action_items = {'VAR':([0,7,8,10,22,24,25,26,27,],[6,11,21,21,21,21,21,21,21,]),'?':([0,],[7,]),'!':([0,],[8,]),'*':([0,15,16,17,18,19,20,21,29,30,31,32,33,],[9,26,-14,-15,-16,-19,-20,-21,26,26,-17,-18,-22,]),'$end':([1,2,3,4,5,9,11,12,13,14,15,16,17,18,19,20,21,23,29,30,31,32,33,],[0,-1,-2,-3,-4,-8,-6,-7,-9,-10,-11,-14,-15,-16,-19,-20,-21,-5,-13,-12,-17,-18,-22,]),'=':([6,],[10,]),'NUM':([8,10,22,24,25,26,27,],[19,19,19,19,19,19,19,]),'(':([8,10,22,24,25,26,27,],[22,22,22,22,22,22,22,]),'-':([12,13,14,15,16,17,18,19,20,21,23,28,29,30,31,32,33,],[24,-9,-10,-11,-14,-15,-16,-19,-20,-21,24,24,-13,-12,-17,-18,-22,]),'+':([12,13,14,15,16,17,18,19,20,21,23,28,29,30,31,32,33,],[25,-9,-10,-11,-14,-15,-16,-19,-20,-21,25,25,-13,-12,-17,-18,-22,]),')':([13,14,15,16,17,18,19,20,21,28,29,30,31,32,33,],[-9,-10,-11,-14,-15,-16,-19,-20,-21,33,-13,-12,-17,-18,-22,]),'/':([15,16,17,18,19,20,21,29,30,31,32,33,],[27,-14,-15,-16,-19,-20,-21,27,27,-17,-18,-22,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Calculadora':([0,],[1,]),'ATRIB':([0,],[2,]),'VALVAR':([0,],[3,]),'VALEXP':([0,],[4,]),'DUMP':([0,],[5,]),'EXP':([8,10,22,],[12,23,28,]),'MENOS':([8,10,22,],[13,13,13,]),'MAIS':([8,10,22,],[14,14,14,]),'TERM':([8,10,22,24,25,],[15,15,15,29,30,]),'MULT':([8,10,22,24,25,],[16,16,16,16,16,]),'DIV':([8,10,22,24,25,],[17,17,17,17,17,]),'FACTOR':([8,10,22,24,25,26,27,],[18,18,18,18,18,31,32,]),'PA':([8,10,22,24,25,26,27,],[20,20,20,20,20,20,20,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Calculadora","S'",1,None,None,None),
  ('Calculadora -> ATRIB','Calculadora',1,'p_calculadora','parser.py',6),
  ('Calculadora -> VALVAR','Calculadora',1,'p_calculadora','parser.py',7),
  ('Calculadora -> VALEXP','Calculadora',1,'p_calculadora','parser.py',8),
  ('Calculadora -> DUMP','Calculadora',1,'p_calculadora','parser.py',9),
  ('ATRIB -> VAR = EXP','ATRIB',3,'p_atrib','parser.py',15),
  ('VALVAR -> ? VAR','VALVAR',2,'p_valvar','parser.py',22),
  ('VALEXP -> ! EXP','VALEXP',2,'p_valexp','parser.py',27),
  ('DUMP -> *','DUMP',1,'p_dump','parser.py',33),
  ('EXP -> MENOS','EXP',1,'p_exp','parser.py',41),
  ('EXP -> MAIS','EXP',1,'p_exp','parser.py',42),
  ('EXP -> TERM','EXP',1,'p_exp','parser.py',43),
  ('MAIS -> EXP + TERM','MAIS',3,'p_mais','parser.py',49),
  ('MENOS -> EXP - TERM','MENOS',3,'p_menos','parser.py',58),
  ('TERM -> MULT','TERM',1,'p_term','parser.py',68),
  ('TERM -> DIV','TERM',1,'p_term','parser.py',69),
  ('TERM -> FACTOR','TERM',1,'p_term','parser.py',70),
  ('MULT -> TERM * FACTOR','MULT',3,'p_mult','parser.py',76),
  ('DIV -> TERM / FACTOR','DIV',3,'p_div','parser.py',82),
  ('FACTOR -> NUM','FACTOR',1,'p_factor','parser.py',88),
  ('FACTOR -> PA','FACTOR',1,'p_factor','parser.py',89),
  ('FACTOR -> VAR','FACTOR',1,'p_factor','parser.py',90),
  ('PA -> ( EXP )','PA',3,'p_parent','parser.py',96),
]
