
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "INTS : Exp '.'Exp : INTExp : '(' Funcao ')'Funcao : '+' ListaFuncao : '*' ListaLista : Exp ListaLista : Exp"
    
_lr_action_items = {'INT':([0,3,7,8,9,11,],[3,-2,3,3,-3,3,]),'(':([0,3,7,8,9,11,],[4,-2,4,4,-3,4,]),'$end':([1,5,],[0,-1,]),'.':([2,3,9,],[5,-2,-3,]),')':([3,6,9,10,11,12,13,],[-2,9,-3,-4,-7,-5,-6,]),'+':([4,],[7,]),'*':([4,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'S':([0,],[1,]),'Exp':([0,7,8,11,],[2,11,11,11,]),'Funcao':([4,],[6,]),'Lista':([7,8,11,],[10,12,13,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> S","S'",1,None,None,None),
  ('S -> Exp .','S',2,'p_S','parser_num.py',8),
  ('Exp -> INT','Exp',1,'p_Exp_int','parser_num.py',12),
  ('Exp -> ( Funcao )','Exp',3,'p_Exp_funcao','parser_num.py',16),
  ('Funcao -> + Lista','Funcao',2,'p_Funcao_mais','parser_num.py',20),
  ('Funcao -> * Lista','Funcao',2,'p_Funcao_vezes','parser_num.py',24),
  ('Lista -> Exp Lista','Lista',2,'p_Lista_rec','parser_num.py',28),
  ('Lista -> Exp','Lista',1,'p_Lista_single','parser_num.py',32),
]
