
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "INTSexp : Exp '.'Exp : INTExp : '(' Funcao ')'Funcao : '+' ListaFuncao : '*' ListaLista : Lista ExpLista : "
    
_lr_action_items = {'INT':([0,3,7,8,9,10,11,12,],[3,-2,-7,-7,-3,3,3,-6,]),'(':([0,3,7,8,9,10,11,12,],[4,-2,-7,-7,-3,4,4,-6,]),'$end':([1,5,],[0,-1,]),'.':([2,3,9,],[5,-2,-3,]),')':([3,6,7,8,9,10,11,12,],[-2,9,-7,-7,-3,-4,-5,-6,]),'+':([4,],[7,]),'*':([4,],[8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Sexp':([0,],[1,]),'Exp':([0,10,11,],[2,12,12,]),'Funcao':([4,],[6,]),'Lista':([7,8,],[10,11,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Sexp","S'",1,None,None,None),
  ('Sexp -> Exp .','Sexp',2,'p_Sexp','sexp_sin.py',15),
  ('Exp -> INT','Exp',1,'p_Exp_INT','sexp_sin.py',20),
  ('Exp -> ( Funcao )','Exp',3,'p_Exp_Funcao','sexp_sin.py',24),
  ('Funcao -> + Lista','Funcao',2,'p_Funcao_add','sexp_sin.py',28),
  ('Funcao -> * Lista','Funcao',2,'p_Funcao_mul','sexp_sin.py',32),
  ('Lista -> Lista Exp','Lista',2,'p_Lista_lista','sexp_sin.py',36),
  ('Lista -> <empty>','Lista',0,'p_Lista_elem','sexp_sin.py',40),
]
